# -*- mode: ruby -*-
# vi: set ft=ruby :

# Specify Vagrant version, Vagrant API version, and Vagrant clone location
Vagrant.require_version '>= 1.6.0'
VAGRANTFILE_API_VERSION = '2'

# Require 'yaml' module
require 'yaml'

# Read YAML file with VM details (box, CPU, and RAM)
servers = YAML.load_file(File.join(File.dirname(__FILE__), 'servers.yml'))

# Create and configure the VMs
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  # Always use Vagrant's default insecure key
  config.ssh.insert_key = false

  # Iterate through entries in YAML file to create VMs
  servers.each do |servers|
    config.vm.define servers['name'] do |srv|

      # Don't check for box updates
      srv.vm.box_check_update = false
      srv.vm.hostname = servers['name']
      srv.vm.box = servers['vmw_box']

      # Disable default synced folder
      srv.vm.synced_folder '.', '/vagrant', disabled: true

      srv.vm.provider :digital_ocean do |digitalo, override|
        override.vm.box = 'digital_ocean'
        override.ssh.private_key_path = '../keys/linuxconeulab'
        digitalo.token = ENV['DO_TOKEN']
        digitalo.ssh_key_name = 'linuxconeulab'
        digitalo.image = servers['digitalo_image']
        digitalo.region = 'nyc3'
        digitalo.size = '2gb'
      end
      # Configure VMs with RAM and CPUs per settings in servers.yml (VirtualBox)
    end # config.vm.define
  end # servers.each

#  config.vm.provision :shell, :path => '../scripts/common.sh'
#  config.vm.provision :shell, :path => '../scripts/docker.sh'
end # Vagrant.configure
