version: '2'
services:
  zookeeper:
    image: mesoscloud/zookeeper:3.4.8-ubuntu-14.04
    network_mode: "host"
    environment:
       - MYID=1
       - SERVERS=${HOST_IP}
  
  master:
    image: mesosphere/mesos-master:1.1.01.1.0-2.0.107.ubuntu1404
    network_mode: "host"
    environment:
      - MESOS_HOSTNAME=${HOST_IP}
      - MESOS_IP=${HOST_IP}
      - MESOS_QUORUM=1
      - MESOS_ZK=zk://${HOST_IP}:2181/mesos
  
  slave:
    image: mesosphere/mesos-slave:1.1.0-2.0.107.ubuntu1404
    network_mode: "host"
    privileged: true
    environment:
      - MESOS_HOSTNAME=${HOST_IP}
      - MESOS_IP=${HOST_IP}
      - MESOS_PORT=5051
      - MESOS_MASTER=zk://${HOST_IP}:2181/mesos
      - MESOS_CONTAINERIZERS=docker,mesos
      - MESOS_WORK_DIR=/var/tmp/mesos
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup
      - /var/run/docker.sock:/var/run/docker.sock
  
  marathon:
    image: mesosphere/marathon:v1.4.0-RC8
    network_mode: "host"
    environment:
      - MARATHON_HOSTNAME=${HOST_IP}
      - MARATHON_HTTPS_ADDRESS=${HOST_IP}
      - MARATHON_HTTP_ADDRESS=${HOST_IP}
      - MARATHON_MASTER=zk://${HOST_IP}:2181/mesos
      - MARATHON_ZK=zk://${HOST_IP}:2181/marathon
  
  chronos:
    image: mesoscloud/chronos
    network_mode: "host"
    environment:
     - CHRONOS_HTTP_PORT=4400
     - CHRONOS_MASTER=zk://${HOST_IP}:2181/mesos
     - CHRONOS_ZK_HOSTS=${HOST_IP}:2181
  
  dns:
    image: tobilg/mesos-dns
    network_mode: "host"
    environment:
     - MESOS_ZK=zk://${HOST_IP}:2181/mesos
     - LOCAL_IP=${HOST_IP} 
     - MESOS_DNS_EXTERNAL_SERVERS=8.8.8.8,8.8.4.4
